language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=free)
  - secure: fv//L/MM4E/KwQwzcycAf9Y7yFadEHnmrlByE4zDcVfdjU8d21uvFl4vM2NInz7tLOZBxVr11fI8yxNgLDLQMFT0qZ0UfmKuKx5CcFBrMWU2iVnJdlBD9RlocgvIXpzbD9pyh4DLAEXVdVIXRGy7agiraW76F64Q/sENsH3vX54ODBgzNOjelw7vMWnC7hBIsWkWTsuyKfoeukjuobxkWj8xlVxu5Xo4DIQA8Q3Slv6OZHXTmhRwkRMYc66oV4hU/fiHfhbKkDiIIrrjzge1WnC5lt9KecqoQblZd17KcMsZt/zJlSLCPhx83vlFsJ1lubGL9b8dzZr2YNElxhRQmfVQcQOt5ZXAdcoyn9S33W8ei30tgBPT2Asfv83bZCSQp3UeSZpWTRGhT5IgMJnRDQZ8zYNAAtwOBPAoTZ/wb3o2SwY0expUsLVFYNHwRYfktKSMsWwUQZTDyPa4JbAQhKqjTlRze8MyG/9o9bpD0sd4NiypSkDQEKUfHNWbOMmEyhD+D4MLt0ulSe2wbgWW0GHMvMziFvt2VlmvdR6jRD2TzTLa/aqj5bBiFRmcXj8mtm/dv+xuy7qK+0c7LDinx6dpjuuEA6BeN9frPI3ZSqwGiVaLLTmnPmjjPMQV5HAJSYx2BOPXgRUfVCx8yB6xQcpf/EFwZ+4mt2NU2kZc6OA=
  # MATTERMOST_HOOK_URL
  - secure: iT1rJwXC+Wq51tVqTPgDUPIqblSsgLdPydsKJI/mxJHp1fmc5/bi+1kcj42kmzlTLdjDJtDFLDRUCg2WzYuLxK4m+bgEZKEg9309Zr6/cklTxZcs4rbEAaUEWj6aGWtrqG5+5z6hz9zVO99cpv1BsnADnQ9RXJP2Re6SgCpWl/bbPfAR4Ee0yyFMiD//VC7o0M9q6hdNGtkIyRl6SGOctAbboOoqQm0qdj11pMfL0PS5UbIMyteUXTFWmSR2zb3ZWAbeZX9vA89WdZcvrGZpN91cMwDWc0BPrej0uYltB9PteZiMEtVJKxcvlEnB6+T1bf3FUZbASM+AxKPSozphL6B+0J0/lx4wimyeJMt3WHT5wUTYgJlO5JCwo8rhM1FjVYG4TwXITvKg3AtXq7gPV7z3Y9roD0GwxmeXU+yfmVKTQEjoni7WzJPxXzqcnQIOhQ/JSGo/OJX3aEfvbCoXxBMsAIhJAc6stOfPwqRL36bADmb5qSc4/xZOYO5/P0D8FWKhUe3PxKm9/yroYcesG3d0qLNmvPQWSKMtJDF+0XJms5zzuXMFRYn4KR8+pIDaBFzFbnGbP5oSvNZ/+BINE6b3q79XzGWscdDT0l4k0eziCddaCyOU3bKGFtO5jDkkhfybboe0GNoLmbJPcMKMOs0PUFan1wHP+v7CoxFRnEA=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
